### ISSUE TITLE
PSP 1000 Vitabright 1.0

### ISSUE THREAD

**Issue by Ehren1337** [devnoname120/vitabright#19]
After i installed Vitabright 1.0 version and then restart the PS Vita. It shows up like slight orange color with line on right side that has regular color. i thought it might be just the plugin so i deleted it then restarted it and still shows up same issue. So im thinking maybe Vitabright overwrited the gamma thing on factory settings or it messed up my screen. It was perfectly fine before i bothered Vitabright. Currently using 3.65 Enso.

**Comment by devnoname120** [comment]
Vitabright does not change any factory settings or anything. It only applies its changes temporarily.
I think that your issue is unrelated to Vitabright, this is the first time I ever hear about this issue, and this in spite of the large user base.

Note that if you used regularly your Vita on the highest brightness setting with Vitabright enabled it would be different. But here it seems that you barely used Vitabright that your issue happened.
