### ISSUE TITLE
gamma table not used on start

### ISSUE THREAD

**Issue by devnoname120** [devnoname120/vitabright#7]
Need to send the new gamma line to the screen by doing this after LUT injection:
```c
ksceOledSetBrightness(ksceOledGetBrightness());
```

**Comment by eiiiiix** [comment]
best way i can think of doing this would be 
get the current value > maximum > minimum > original value

**Comment by eiiiiix** [comment]
Fix: load bootconfig from ux0: and config from ur0:
Breaks wireless controllers but autoloads gamma

**Comment by devnoname120** [comment]
> get the current value > maximum > minimum > original value

I have no idea what you mean. Getting the current value is not something that can fail, why would I fall back to those values? 

> Fix: load bootconfig from ux0: and config from ur0:

Vitabright already tries to load from ur0 and if it fails from ux0.

**Comment by eiiiiix** [comment]
I have my bootconfig loading from ux0:tai/eix/boot.txt and have umount_bootfs  removed
and i have all my plugins and my config loading from ur0:tai/eix/ and ur0:tai/
When i boot like this it will auto set to the custom gamma
Wireless controllers like the ds4 and wiimote (when used with nunchuk) break with it like this
But i think the wireless controller issue is just me having so many plugins being loaded
I dont have my vita on me since im in the er but im pretty sure having 60? Plugins is breaking wireless controllers
I have no idea why doing what i did works but it does
